# Copyright (c) 2026 Simon D. Levy
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

load:
	./load.py $(fr)/cpp-apps/networks/dronepong_risp_train.txt

newload:
	./newload.py $(fr)/cpp-apps/networks/dronepong_risp_train.txt

clean:
	rm -rf ~/.cache/neuro_fpga/
